# -*- coding: utf-8 -*-

# DO NOT EDIT THIS FILE!
# This file has been autogenerated by dephell <3
# https://github.com/dephell/dephell

try:
    from setuptools import setup
except ImportError:
    from distutils.core import setup

import os.path

readme = ''
here = os.path.abspath(os.path.dirname(__file__))
readme_path = os.path.join(here, 'README.rst')
if os.path.exists(readme_path):
    with open(readme_path, 'rb') as stream:
        readme = stream.read().decode('utf8')

setup(
    long_description=readme,
    name='django-multifactor',
    version='0.3.15',
    description='Drop-in multifactor authentication subsystem for Django.',
    python_requires='==3.*,>=3.5.0',
    project_urls={
        "homepage": "https://github.com/oliwarner/django-multifactor",
        "repository": "https://github.com/oliwarner/django-multifactor"
    },
    author='Oli Warner',
    author_email='oli@thepcspy.com',
    license='MIT',
    classifiers=[
        'License :: OSI Approved :: MIT License',
        'Development Status :: 4 - Beta', 'Environment :: Web Environment',
        'Framework :: Django', 'Framework :: Django :: 2.2',
        'Intended Audience :: Developers', 'Operating System :: OS Independent',
        'Programming Language :: Python',
        'Programming Language :: Python :: 3.5',
        'Programming Language :: Python :: 3.6',
        'Programming Language :: Python :: 3.7',
        'Programming Language :: Python :: 3.8',
        'Topic :: Software Development :: Libraries :: Python Modules'
    ],
    packages=['multifactor', 'multifactor.factors', 'multifactor.migrations'],
    package_dir={"": "."},
    package_data={
        "multifactor": [
            "static/multifactor/*.svg", "static/multifactor/css/*.css",
            "static/multifactor/js/*.js", "templates/multifactor/*.html",
            "templates/multifactor/FIDO2/*.html",
            "templates/multifactor/TOTP/*.html",
            "templates/multifactor/U2F/*.html",
            "templates/multifactor/fallback/*.html"
        ]
    },
    install_requires=[
        'django==2.*,>=2.2.0', 'fido2==0.7.2', 'pyotp==2.*,>=2.3.0',
        'python-jose==3.*,>=3.0.0', 'python-u2flib-server==5.*,>=5.0.0'
    ],
    extras_require={"dev": ["pytest==3.*,>=3.0.0", "pytest-cov==2.*,>=2.4.0"]},
)
