[tox]
isolated_build = true
requires = coverage
skip_missing_interpreters = true
envlist =
    py310-django52
    py311-django52
    py312-django{61,60,52}
    py313-django{61,60,52}
    py314-django{61,60,52}
    py315-django{61,60,52}

[pytest]
django_find_project = false

[testenv]
deps =
    coverage
    pytest
    pytest-django
    django-decorator-include
    django_extensions
    django-debug-toolbar
    django52: Django>=5.2,<5.3
    django60: Django>=6.0,<6.1
    django61: Django>=6.1a1,<6.2
setenv =
    DJANGO_SETTINGS_MODULE = testsite.testsite.settings
    PYTHONPATH = {toxinidir}
commands =
    python -m coverage run -p -m pytest {posargs}

[testenv:py310-django60]
skip_install = true
commands = python -c "raise SystemExit('Django 6.0 is not supported on Python 3.10')"

[testenv:py310-django61]
skip_install = true
commands = python -c "raise SystemExit('Django 6.1 is not supported on Python 3.10')"

[testenv:py311-django60]
skip_install = true
commands = python -c "raise SystemExit('Django 6.0 is not supported on Python 3.11')"

[testenv:py311-django61]
skip_install = true
commands = python -c "raise SystemExit('Django 6.1 is not supported on Python 3.11')"